#!/bin/bash

REGION=nymtc

# https://stackoverflow.com/a/69179997/3970755
java \
  --add-opens=java.base/java.lang=ALL-UNNAMED \
  --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
  --add-opens=java.base/java.io=ALL-UNNAMED \
  --add-opens=java.base/java.util=ALL-UNNAMED \
  -Xmx2G \
  -jar ./lib/otp-2.1.0-shaded.jar \
  --build \
  --save \
  bundles/$REGION
