#!/bin/bash

VERSION=3.4.0

set -e

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

cd ./versions/$VERSION/ubuntu-full/

docker \
  build \
    --tag avail/osgeo-gdal-ubuntu-full:$VERSION \
    --build-arg GDAL_VERSION=v$VERSION \
    --build-arg WITH_FILEGDB=yes \
  .

popd >/dev/null
